#!/usr/bin/env bash

# Create a network namespace with a WireGuard interface and route all
# traffic through it. The WireGuard interface is configured to use
# NordVPN.
#
# Usage:
# $0 [up|down]
# Some configuration is available through environment variables
# See manual for details

set -euo pipefail
set -x

# The name to be used for the namespace, link name and config file name
WG_NAME=${WG_NAME:-"nordvpn"}

# The WireGuard interface IP address. Defaults to the address which
# the `nordvpn` command assigns to the interface (10.5.0.2/32).
WG_IP=${WG_IP:-"10.5.0.2/32"}

# The country code to use for the NordVPN server. Default to Switzerland.
WG_COUNTRY_CODE=${WG_COUNTRY_CODE:-"CH"}

# A file containing the WireGuard private key.
WG_PRIVATE_KEY="${CREDENTIALS_DIRECTORY:-/etc/nordvpn-netns}/${WG_NAME}.key"

WG_VETH_SUBNET="${WG_VETH_SUBNET:-}"

# veth configuration
if [[ -n $WG_VETH_SUBNET ]]; then
    WG_HOST_VETH=${WG_HOST_VETH:-"${WG_NAME}-host"}
    WG_NETNS_VETH=${WG_NETNS_VETH:-"${WG_NAME}-netns"}

    # Calculate IP addresses
    eval $(ipcalc ${WG_VETH_SUBNET} -s 2 | sed \
      -e '/^HostM/!d' \
      -e 's/HostMin/WG_HOST_VETH_ADDR/' \
      -e 's/HostMax/WG_NETNS_VETH_ADDR/' \
      -e 's/: */=/' \
      -e 's/ .*//' \
      | tail -2)
fi

# The command to run. Either `up` or `down`.
COMMAND="$1"

recommended_nordvpn_server() {
  local url response country_id
  echo >&2 "Finding recommended NordVPN server for country code ${WG_COUNTRY_CODE}"

  # Get the country ID from the country code
  url="https://api.nordvpn.com/v1/servers/countries"
  country_id=$(curl --silent --show-error "${url}" | jq -r ".[] | select(.code == \"${WG_COUNTRY_CODE}\") | .id")

  # Get the recommended server for the country
  url="https://api.nordvpn.com/v1/servers/recommendations\
?filters\[country_id\]=${country_id}\
&\[servers_technologies\]\[identifier\]=wireguard_udp\
&\[servers_groups\]\[identifier\]=P2P\
&limit=1"
  response=$(curl --silent --show-error "${url}")

  # Print the hostname and public key
  jq '.[] |
    {
      hostname,
      public_key: (
        .technologies[] |
        select(.identifier == "wireguard_udp").metadata[] |
        select(.name == "public_key").value
      )
    }' <<< "${response}"
}

up() {
    local recommended_server hostname public_key

    # Ensure that the namespace is down before starting
    down >/dev/null 2>&1 || true

    echo >&2 "Starting namespace ${WG_NAME}"

    # Create the namespace
    ip netns add "${WG_NAME}"

    # Set the loopback interface up (required for transmission to be
    # able to bind to the interface)
    ip -n "${WG_NAME}" link set lo up

    # Create the WireGuard interface
    ip link add "${WG_NAME}" type wireguard

    recommended_server=$(recommended_nordvpn_server)
    hostname=$(jq -r '.hostname' <<< "${recommended_server}")
    public_key=$(jq -r '.public_key' <<< "${recommended_server}")

    echo >&2 "Connecting to ${hostname}"

    # Assert that the hostname starts with the country code in lowercase.
    # The double comma is a bashism to convert the variable to lowercase.
    if [[ ! "${hostname}" =~ ^"${WG_COUNTRY_CODE,,}" ]]; then
        echo >&2 "Hostname ${hostname} does not start with ${WG_COUNTRY_CODE,,}"
        exit 1
    fi

    # Set the WireGuard private key and peer. Do this before moving the
    # interface into the namespace so that the hostname can be resolved.
    wg set "${WG_NAME}" \
       private-key "${WG_PRIVATE_KEY}" \
       peer "${public_key}" \
       endpoint "${hostname}:51820" \
       allowed-ips 0.0.0.0/0,::0/0

    # Move the WireGuard interface into the namespace
    ip link set "${WG_NAME}" netns "${WG_NAME}"

    # Configure the WireGuard interface
    ip -n "${WG_NAME}" addr add "${WG_IP}" dev "${WG_NAME}"
    ip -n "${WG_NAME}" link set mtu 1420 up dev "${WG_NAME}"

    # Route all traffic through the WireGuard interface
    ip -j -n "${WG_NAME}" route add default dev "${WG_NAME}"

    # Set up veth link if requested
    if [[ -n $WG_VETH_SUBNET ]]; then
        # Create links
        ip link add "${WG_HOST_VETH}" type veth peer name "${WG_NETNS_VETH}"

        # Move netns veth into namespace
        ip link set "${WG_NETNS_VETH}" netns "${WG_NAME}"

        # Assign addresses & bring up links
        ip addr add "${WG_HOST_VETH_ADDR}/30" dev "${WG_HOST_VETH}"
        ip link set "${WG_HOST_VETH}" up

        ip -n "${WG_NAME}" addr add "${WG_NETNS_VETH_ADDR}/30" dev "${WG_NETNS_VETH}"
        ip -n "${WG_NAME}" link set "${WG_NETNS_VETH}" up
    fi

    echo >&2 "Namespace ${WG_NAME} is up"

    if [[ -v NOTIFY_SOCKET ]]; then
        echo >&2 "Signalling readiness to systemd via sd_notify"
        systemd-notify --ready
    fi
}

down() {
    echo >&2 "Stopping namespace ${WG_NAME}"
    ip -n "${WG_NAME}" link set down dev "${WG_NAME}" || true
    ip -n "${WG_NAME}" link del dev "${WG_NAME}" || true
    if [[ -n $WG_VETH_SUBNET ]]; then
        ip -n "${WG_NAME}" link set down dev "${WG_NETNS_VETH}" || true
        ip -n "${WG_NAME}" link del dev "${WG_NETNS_VETH}" || true
        ip link set down dev "${WG_HOST_VETH}" || true
        ip link del dev "${WG_HOST_VETH}" || true
    fi
    ip netns del "${WG_NAME}" || true
    ip link del "${WG_NAME}" || true
    echo >&2 "Namespace ${WG_NAME} is down"
}

case "$COMMAND" in
    up) up "$@" ;;
    down) down "$@" ;;
esac
